/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animal.shelter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AnimalTest {
    @Test void canMakeAAnimalShelterTest() {
        AnimalShelter sut = new AnimalShelter("doggy");
        assertEquals("doggy", sut.shelterName);

    }
    @Test void canAddADogToTheAnimalShelterTest() {
      AnimalShelter sut = new AnimalShelter("doggy");
      Dog myDog = new Dog("Dog");

      assertTrue(sut.acceptAnimal(myDog));
    }
    @Test void canAddACatToTheAnimalShelterTest() {
      AnimalShelter sut = new AnimalShelter("catty");
      Cat myCat = new Cat("Cat");

      assertTrue(sut.acceptAnimal(myCat));
  }
    @Test void thereIsEqualAnimalThenGetDogTest() {

  }
    @Test void thereAreMoreCatsThenDogsSoYouGetACatTest() {

  }
}
